[keyboard]
name = "Dactuiyl"
product_name = "Dactuiyl"
vendor_id = 0xFEED
product_id = 0xCAD1
manufacturer = "Artur Bacilla"
serial_number = "vial:f64c2b3c"
chip = "esp32s3"


[layout]
rows = 6
cols = 14
layers = 1

keymap = [
    [
        [
            "F1",
            "F2",
            "F3",
            "F4",
            "F5",
            "F6",
            "LCtrl",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "",
            "",
            "Kc1",
            "Kc2",
            "Kc3",
            "Kc4",
            "LAlt",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "",
            "",
            "Q",
            "W",
            "F",
            "P",
            "Space",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "",
            "",
            "A",
            "R",
            "S",
            "T",
            "lwin",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "",
            "",
            "Z",
            "X",
            "C",
            "D",
            "MO(2)",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "",
            "",
            "LGui",
            "LShift",
            "Delete",
            "MO(6)",
            "TRNS",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
    ],
]

[split]
connection = "serial"

[split.central]
rows = 6
cols = 7
row_offset = 0
col_offset = 0
serial = [{ instance = "UART0", tx_pin = "GPIO43", rx_pin = "GPIO44" }]

[split.central.matrix]
#output colunas
input_pins = ["GPIO1", "GPIO2", "GPIO3", "GPIO4", "GPIO5", "GPIO6"]
output_pins = [
    "GPIO13",
    "GPIO12",
    "GPIO11",
    "GPIO10",
    "GPIO9",
    "GPIO8",
    "GPIO7",
]

[[split.peripheral]]
rows = 6
cols = 7
row_offset = 0
col_offset = 7
serial = [{ instance = "UART0", tx_pin = "GPIO43", rx_pin = "GPIO44" }]

[split.peripheral.matrix]
input_pins = ["GPIO1", "GPIO2", "GPIO3", "GPIO4", "GPIO5", "GPIO6"]
output_pins = [
    "GPIO13",
    "GPIO12",
    "GPIO11",
    "GPIO10",
    "GPIO9",
    "GPIO8",
    "GPIO7",
]
