[keyboard]
name = "Dactuiyl"
product_name = "Dactuiyl"
vendor_id = 0xFEED
product_id = 0xCAD1
manufacturer = "Artur Bacilla"
serial_number = "vial:f64c2b3c"
chip = "esp32s3"


[layout]
rows = 6
cols = 14
layers = 1

keymap = [
    [
        [
            # Left Side
            "F1",
            "F2",
            "F3",
            "F4",
            "F5",
            "F6",
            "LCtrl",
            # Right Side
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            # Left Side
            "LeftBracket",  # [
            "RightBracket", # ]
            "Kc1",
            "Kc2",
            "Kc3",
            "Kc4",
            "LAlt",
            # Right Side
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            # Left Side
            "WM(LeftBracket, LShift)",  # {
            "WM(RightBracket, LShift)", #  }
            "Q",
            "W",
            "F",
            "P",
            "Tab",
            # Right Side
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            # Left Side
            "Backslash", # \|
            "Slash",     # /?
            "A",
            "R",
            "S",
            "T",
            "lwin",
            # Right Side
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            # Left Side
            "CapsLock",
            "Tab",
            "Z",
            "X",
            "C",
            "D",
            "MO(2)",
            # Right Side
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            # Left Side
            "__",
            "__",
            "Minus",
            "Equal",
            "LShift",
            "__",
            "TRNS",
            # Right Side
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
    ],
]

# [storage]
# enabled = false

# [dependency]
# defmt_log = false

# [host]
# vial_enabled = true

[split]
connection = "ble"

[split.central]
rows = 6
cols = 7
row_offset = 0
col_offset = 0
# serial = [{ instance = "UART0", tx_pin = "GPIO43", rx_pin = "GPIO44" }]

[split.central.matrix]
#output colunas
matrix_type = "normal"
row_pins = ["GPIO1", "GPIO2", "GPIO3", "GPIO4", "GPIO5", "GPIO6"]
col_pins = ["GPIO13", "GPIO12", "GPIO11", "GPIO10", "GPIO9", "GPIO8", "GPIO7"]

[[split.peripheral]]
rows = 6
cols = 7
row_offset = 0
col_offset = 7
# serial = [{ instance = "UART0", tx_pin = "GPIO43", rx_pin = "GPIO44" }]

[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["GPIO1", "GPIO2", "GPIO3", "GPIO4", "GPIO5", "GPIO6"]
col_pins = ["GPIO13", "GPIO12", "GPIO11", "GPIO10", "GPIO9", "GPIO8", "GPIO7"]
