[keyboard]
name = "Dactuiyl"
product_name = "Dactuiyl"
vendor_id = 0xFEED
product_id = 0xCAD1
manufacturer = "Artur Bacilla"
serial_number = "vial:f64c2b3c"
chip = "esp32s3"


[layout]
rows = 6
cols = 14
layers = 2

keymap = [
    [
        [
            # Left Side
            "F1",
            "F2",
            "F3",
            "F4",
            "F5",
            "F6",
            "LCtrl",
            # Right Side
            "Backspace",
            "F7",
            "F8",
            "F9",
            "F10",
            "F11",
            "F12"
        ],
        [
            # Left Side
            "LeftBracket",  # [
            "RightBracket", # ]
            "Kc1",
            "Kc2",
            "Kc3",
            "Kc4",
            "LAlt",
            # Right Side
            "Space",
            "Kc5",
            "Kc6",
            "Kc7",
            "Kc8",
            "Kc9",
            "Kc0"
        ],
        [
            # Left Side
            "WM(LeftBracket, LShift)",  # {
            "WM(RightBracket, LShift)", #  }
            "Q",
            "W",
            "F",
            "P",
            "Tab",
            # Right Side
            "Escape",
            "U",
            "L",
            "J",
            "G",
            "__",     # Ç
            "Y"
        ],
        [
            # Left Side
            "Backslash", # \|
            "Slash",     # /?
            "A",
            "R",
            "S",
            "T",
            "lwin",
            # Right Side
            "Delete",
            "M",
            "N",
            "E",
            "I",
            "__",     # ~^
            "K"
        ],
        [
            # Left Side
            "CapsLock",
            "Tab",
            "Z",
            "X",
            "C",
            "D",
            "MO(2)",
            # Right Side
            "PrintScreen",
            "V",
            "H",
            "B",
            "O",
            "Semicolon",
            "__"
        ],
        [
            # Left Side
            "__",
            "__",
            "Minus",
            "Equal",
            "LShift",
            "__",
            "TRNS",
            # Right Side
            "__",
            "__",
            "Enter",
            "Comma",
            "Dot",
            "__",
            "__"
        ]
    ],
    [
        [
            # Left Side
            "F1",
            "F2",
            "F3",
            "F4",
            "F5",
            "F6",
            "LCtrl",
            # Right Side
            "Backspace",
            "F7",
            "F8",
            "F9",
            "F10",
            "F11",
            "F12"
        ],
        [
            # Left Side
            "LeftBracket",  # [
            "RightBracket", # ]
            "Kc1",
            "Kc2",
            "Kc3",
            "Kc4",
            "LAlt",
            # Right Side
            "Space",
            "Kc5",
            "Kc6",
            "Kc7",
            "Kc8",
            "Kc9",
            "Kc0"
        ],
        [
            # Left Side
            "WM(LeftBracket, LShift)",  # {
            "WM(RightBracket, LShift)", #  }
            "Q",
            "W",
            "E",
            "R",
            "Tab",
            # Right Side
            "Escape",
            "T",
            "Y",
            "U",
            "I",
            "O",
            "P"
        ],
        [
            # Left Side
            "Backslash", # \|
            "Slash",     # /?
            "A",
            "S",
            "D",
            "F",
            "lwin",
            # Right Side
            "Delete",
            "G",
            "H",
            "J",
            "K",
            "L",
            "__"      #Ç
        ],
        [
            # Left Side
            "CapsLock",
            "Tab",
            "Z",
            "X",
            "C",
            "V",
            "MO(2)",
            # Right Side
            "PrintScreen",
            "B",
            "N",
            "M",
            "O",
            "Semicolon",
            "__"
        ],
        [
            # Left Side
            "__",
            "__",
            "Minus",
            "Equal",
            "LShift",
            "__",
            "TRNS",
            # Right Side
            "__",
            "__",
            "Enter",
            "Comma",
            "Dot",
            "__",
            "__"
        ]
    ]

]

# [storage]
# enabled = false

# [dependency]
# defmt_log = false

# [host]
# vial_enabled = true

[split]
connection = "ble"

[split.central]
rows = 6
cols = 7
row_offset = 0
col_offset = 0
# serial = [{ instance = "UART0", tx_pin = "GPIO43", rx_pin = "GPIO44" }]

[split.central.matrix]
#output colunas
matrix_type = "normal"
row_pins = ["GPIO1", "GPIO2", "GPIO3", "GPIO4", "GPIO5", "GPIO6"]
col_pins = ["GPIO13", "GPIO12", "GPIO11", "GPIO10", "GPIO9", "GPIO8", "GPIO7"]

[[split.peripheral]]
rows = 6
cols = 7
row_offset = 0
col_offset = 7
# serial = [{ instance = "UART0", tx_pin = "GPIO43", rx_pin = "GPIO44" }]

[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["GPIO6", "GPIO5", "GPIO4", "GPIO3", "GPIO2", "GPIO1"]
col_pins = ["GPIO7", "GPIO8", "GPIO9", "GPIO10", "GPIO11", "GPIO12", "GPIO13"]
